[[hooks]]
name = "echo"
workdir = "/"
command = "cat"

[[hooks]]
name = "count"
workdir = "/"
command = "wc -l"

[[hooks]]
name = "inline"
inline = """
content=$(cat)
echo "== echo =="
echo -E "${content}"
echo "== count =="
echo -E "${content}" | wc -c
"""
